#!/bin/sh

DATADIR=data

mkdir -p $DATADIR/data $DATADIR/metadata

if [ ! -d $DATADIR ]
then
	rm -rf $DATADIR
	echo "test database dir not found."
	exit 1
fi

../nfs4dba -D $PWD/data/data -M $PWD/data/metadata -I

exit 0
