#!/bin/sh

if [ -f nfs4d.pid ]
then
	echo "pid file found.  daemon still running?"
	exit 1
fi

../nfs4d -D $PWD/data/data -M $PWD/data/metadata -P $PWD/nfs4d.pid	\
	-E -b localhost.localdomain:22049

sleep 2

exit 0
