/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <memory.h>
#include <locale.h>
#include <unistd.h>
#include <syslog.h>
#include <time.h>
#include <sys/time.h>
#include <rpc/pmap_clnt.h>
#include <netinet/in.h>
#include "server.h"
#include "nfs4_prot.h"


enum {
	NFS_PORT		= 2049,
	LISTEN_SIZE		= 100,
};

struct timeval current_time;
GList *client_list = NULL;
struct nfs_server srv;


static void slerror(const char *prefix)
{
	syslog(LOG_ERR, "%s: %s", prefix, strerror(errno));
}

static void init_rng(void)
{
	unsigned long v;
	int fd;
	ssize_t bytes;

	fd = open("/dev/random", O_RDONLY);
	if (fd < 0) {
		slerror("/dev/random");
		goto srand_time;
	}

	bytes = read(fd, &v, sizeof(v));
	if (bytes < 0)
		slerror("/dev/random read");
		
	close(fd);

	if (bytes < sizeof(v))
		goto srand_time;

	srand48_r(v, &srv.rng);
	return;

srand_time:
	srand48_r(getpid() ^ time(NULL), &srv.rng);
}

static int init_sock(void)
{
	int sock, val;
	struct sockaddr_in saddr;

	sock = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
	if (sock < 0) {
		slerror("socket");
		return -1;
	}

	val = 1;
	if (setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &val,
		       sizeof(val)) < 0) {
		slerror("setsockopt");
		return -1;
	}

	memset(&saddr, 0, sizeof(saddr));
	saddr.sin_family = AF_INET;
	saddr.sin_port = htons(NFS_PORT);
	saddr.sin_addr.s_addr = htonl(INADDR_ANY);
	if (bind(sock, (struct sockaddr *)&saddr, sizeof(saddr)) < 0) {
		slerror("bind");
		return -1;
	}

	if (listen(sock, LISTEN_SIZE) < 0) {
		slerror("listen");
		return -1;
	}

	return sock;
}

static enum auth_stat check_auth(struct svc_req *rqstp)
{
	switch (rqstp->rq_cred.oa_flavor) {
	case AUTH_SYS:
		return AUTH_OK;
	default:
		return AUTH_TOOWEAK;
	}

	return AUTH_FAILED;	/* never reached; kill warning */
}

static void
nfs4_program_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	COMPOUND4args argument;
	COMPOUND4res result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);
	enum auth_stat auth_stat;
	struct timezone tz = { 0, 0 };

	switch (rqstp->rq_proc) {
	case NFSPROC4_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc4_null_4_svc;
		break;

	case NFSPROC4_COMPOUND:
		_xdr_argument = (xdrproc_t) xdr_COMPOUND4args;
		_xdr_result = (xdrproc_t) xdr_COMPOUND4res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc4_compound_4_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}

	gettimeofday(&current_time, &tz);

	auth_stat = check_auth(rqstp);
	if (auth_stat != AUTH_OK) {
		retval = FALSE;
		svcerr_auth(transp, auth_stat);
	} else
		retval = (bool_t) (*local)((char *)&argument,
					   (void *)&result, rqstp);

	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		syslog(LOG_ERR, "unable to free arguments");
		exit (1);
	}
	if (!nfs4_program_4_freeresult (transp, _xdr_result, &result))
		syslog(LOG_ERR, "unable to free results");

	return;
}

/* Linux is missing this prototype */
#if 0
bool_t gssrpc_pmap_unset(u_long prognum, u_long versnum);
#endif

static int init_rpc(int sock)
{
	register SVCXPRT *transp;

	transp = svctcp_create(sock, 0, 0);
	if (transp == NULL) {
		syslog(LOG_ERR, "cannot create tcp service.");
		return -1;
	}
	if (!svc_register(transp, NFS4_PROGRAM, NFS_V4, nfs4_program_4, IPPROTO_TCP)) {
		syslog(LOG_ERR, "unable to register (NFS4_PROGRAM, NFS_V4, tcp).");
		return -1;
	}

	return 0;
}

static int init_server(void)
{
	struct timezone tz = { 0, 0 };
	int sock;

	pmap_unset (NFS4_PROGRAM, NFS_V4);

	memset(&srv, 0, sizeof(srv));
	srv.lease_time = 5 * 60;
	srv.client_ids = g_hash_table_new_full(clientid_hash, clientid_equal,
					       NULL, state_free);
	srv.clid_idx = g_hash_table_new_full(short_clientid_hash,
					     short_clientid_equal,
					     g_free, NULL);

	if (gettimeofday(&current_time, &tz) < 0) {
		slerror("gettimeofday(2)");
		return -1;
	}

	if (!srv.client_ids || !srv.clid_idx) {
		syslog(LOG_ERR, "OOM in init_server()");
		return -1;
	}

	inode_table_init();

	init_rng();
	rand_verifier(&srv.instance_verf);

	sock = init_sock();
	if (sock < 0)
		return -1;

	if (init_rpc(sock) < 0)
		return -1;

	return 0;
}

int main (int argc, char *argv[])
{
	setlocale(LC_ALL, "");

	openlog("nfs4_ramd", LOG_PID, LOG_LOCAL2);

	if (daemon(0, 0) < 0) {
		slerror("daemon(2)");
		return 1;
	}

	if (init_server())
		return 1;

	svc_run ();

	syslog(LOG_ERR, "svc_run returned");
	return 1;
}

